#!/bin/bash
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# cleanCase
rm -rf 0
rm -rf log.*
rm -fr insitu
rm -fr postProcessing
rm -fr processor*
rm -fr 1* 2* 3* 4* 5* 6* 7* 8* 9*
rm scripts/*.csv scripts/octave-workspace 
